/**
 * Crucibulum — Shared Route Helpers
 * Common utilities for route handlers.
 */

import type { IncomingMessage, ServerResponse } from "node:http";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import type { EvidenceBundle } from "../../adapters/base.js";
import { log } from "../../utils/logger.js";
import { canonicalPercent, type ScoreFamily } from "../../types/scores.js";
import { summarizeBundle, countRepeatRuns, getRelatedBundles } from "../contracts.js";
import { readCrucibleLink } from "../validation-links.js";
import { loadManifestRaw, listTasks } from "../../core/manifest.js";
import { loadVerifiedBundle } from "../../core/bundle.js";

const RUNS_DIR = process.env["CRUCIBULUM_RUNS_DIR"] ?? join(process.cwd(), "runs");
const UI_PATH = join(import.meta.dirname, "..", "..", "ui", "index.html");

export function sendJSON(res: ServerResponse, status: number, data: unknown): void {
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
  });
  res.end(JSON.stringify(data));
}

export async function readBody(req: IncomingMessage): Promise<string> {
  const chunks: Buffer[] = [];
  let total = 0;
  const MAX_BODY = 2 * 1024 * 1024; // 2MB
  for await (const chunk of req) {
    const buf = chunk as Buffer;
    total += buf.length;
    if (total > MAX_BODY) throw new Error("Request body too large");
    chunks.push(buf);
  }
  return Buffer.concat(chunks).toString("utf-8");
}

/**
 * Parse a JSON body with bounded size. Returns [parsed, error]; error is a 400-ready message.
 */
export async function parseJsonBody<T = unknown>(req: IncomingMessage): Promise<{ ok: true; value: T } | { ok: false; error: string }> {
  try {
    const raw = await readBody(req);
    if (!raw.trim()) return { ok: true, value: {} as T };
    return { ok: true, value: JSON.parse(raw) as T };
  } catch (err) {
    return { ok: false, error: `Invalid JSON body: ${String(err)}` };
  }
}

/**
 * Validate a bundle/run ID for safe filesystem use. IDs must be alphanumeric, dash, underscore, dot.
 * Bundle IDs are generated by the system (see bundle.ts:buildBundle) but may come from user-supplied paths.
 */
export function isSafeId(id: string): boolean {
  return typeof id === "string" && id.length > 0 && id.length <= 256 && /^[a-zA-Z0-9._-]+$/.test(id);
}

export function loadBundles(): EvidenceBundle[] {
  try {
    const files = readdirSync(RUNS_DIR).filter(f => f.endsWith(".json") && !f.endsWith(".crucible.json"));
    const bundles: EvidenceBundle[] = [];
    for (const f of files) {
      try {
        const raw = readFileSync(join(RUNS_DIR, f), "utf-8");
        // Re-verifies the bundle hash on every read; tampered/corrupted files get
        // trust.bundle_verified=false instead of silently inheriting the stored flag.
        const bundle = loadVerifiedBundle(raw, f);
        if (bundle) bundles.push(bundle);
        else log("warn", "bundles", `Rejecting malformed bundle file ${f}`);
      } catch (err) {
        // Surface corruption instead of silently hiding it — operators need to see this in logs.
        log("warn", "bundles", `Skipping unparseable bundle file ${f}: ${String(err).slice(0, 120)}`);
      }
    }
    return bundles;
  } catch { return []; }
}

/**
 * Strict lookup by bundle_id. Does NOT fall back to task.id matching —
 * ambiguous dual lookup previously let a task id collide with a bundle id and
 * silently swap which bundle a caller thought they had.
 */
export function getBundleById(id: string): EvidenceBundle | null {
  try {
    const bundles = loadBundles();
    return bundles.find(b => b.bundle_id === id) ?? null;
  } catch { return null; }
}

/** Explicit task-scoped lookup for callers that actually want every bundle for a task. */
export function getBundlesByTaskId(taskId: string): EvidenceBundle[] {
  try {
    return loadBundles().filter(b => b.task.id === taskId);
  } catch { return []; }
}

export function parseFamiliesParam(url: URL): ScoreFamily[] | null {
  const raw = (url.searchParams.get("families") ?? "").trim();
  if (!raw) return null;
  const families = raw.split(",").map(f => f.trim()).filter(Boolean) as ScoreFamily[];
  return families.length > 0 ? families : null;
}

export function filterBundlesByFamilies(bundles: EvidenceBundle[], families: ScoreFamily[] | null): EvidenceBundle[] {
  if (!families || families.length === 0) return bundles;
  const familySet = new Set(families);
  return bundles.filter(b => {
    const taskFamily = b.task.family;
    const mapped = taskFamily.startsWith("poison") ? "A"
      : taskFamily.startsWith("spec") ? "B"
      : taskFamily.startsWith("orchestration") ? "C"
      : taskFamily.startsWith("conversational") ? "D"
      : null;
    return mapped ? familySet.has(mapped) : true;
  });
}

export function listTaskDetails(): Array<Record<string, unknown>> {
  return listTasks().map((task) => {
    const manifest = loadManifestRaw(task.id);
    const isConversational = manifest.execution_mode === "conversational" || !manifest.task;
    return {
      id: manifest.id,
      suite_id: "v1",
      family: manifest.family,
      title: manifest.task?.title ?? manifest.description ?? manifest.id,
      difficulty: manifest.difficulty,
      execution_mode: manifest.execution_mode ?? "repo",
      time_limit_sec: manifest.constraints?.time_limit_sec ?? null,
      max_steps: manifest.constraints?.max_steps ?? null,
      network_allowed: manifest.constraints?.network_allowed ?? false,
      public_tests_command: manifest.verification?.public_tests_command ?? null,
      build_command: manifest.verification?.build_command ?? null,
      question_count: isConversational ? (manifest.questions?.length ?? 0) : null,
      diagnostic_purpose: manifest.metadata?.diagnostic_purpose ?? null,
      tags: manifest.metadata?.tags ?? [],
    };
  });
}

export function listSuites(): Array<Record<string, unknown>> {
  const tasks = listTasks();
  const byFamily = new Map<string, number>();
  for (const task of tasks) {
    byFamily.set(task.family, (byFamily.get(task.family) ?? 0) + 1);
  }
  return [{
    id: "v1",
    label: "Crucibulum v1",
    task_count: tasks.length,
    families: Array.from(byFamily.entries()).map(([family, count]) => ({ family, count })),
  }];
}

export function bundleSummary(bundle: EvidenceBundle, allBundles: EvidenceBundle[]): ReturnType<typeof summarizeBundle> {
  const relatedBundles = getRelatedBundles(allBundles, bundle);
  const repeats = countRepeatRuns(allBundles, bundle.task.id, bundle.agent.adapter, bundle.agent.model, bundle.agent.provider);
  return summarizeBundle(bundle, repeats, readCrucibleLink(bundle.bundle_id), relatedBundles);
}

export function getStats(bundles: EvidenceBundle[]): Record<string, unknown> {
  const totalRuns = bundles.length;
  const passedRuns = bundles.filter(b => b.score.pass).length;
  const totalCost = bundles.reduce((sum, b) => sum + (b.usage.estimated_cost_usd ?? 0), 0);
  const totalTokens = bundles.reduce((sum, b) => sum + (b.usage.tokens_in ?? 0) + (b.usage.tokens_out ?? 0), 0);
  const uniqueModels = new Set(bundles.map(b => b.agent.model)).size;
  const uniqueTasks = new Set(bundles.map(b => b.task.id)).size;
  const avgScore = totalRuns > 0 ? bundles.reduce((sum, b) => sum + canonicalPercent(b.score.total), 0) / totalRuns : 0;
  return {
    total_runs: totalRuns,
    passed_runs: passedRuns,
    pass_rate: totalRuns > 0 ? Math.round((passedRuns / totalRuns) * 100) : 0,
    avg_score: Math.round(avgScore * 100) / 100,
    total_cost_usd: Math.round(totalCost * 10000) / 10000,
    total_tokens: totalTokens,
    unique_models: uniqueModels,
    unique_tasks: uniqueTasks,
  };
}

export { RUNS_DIR, UI_PATH, log, canonicalPercent };
