/**
 * Luak — Shared Route Helpers
 * Common utilities for route handlers.
 */

import type { IncomingMessage, ServerResponse } from "node:http";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import type { EvidenceBundle } from "../../adapters/base.js";
import { log } from "../../utils/logger.js";
import { canonicalPercent, taskFamiliesForScoreFamilies, type ScoreFamily } from "../../types/scores.js";
import { summarizeBundle, countRepeatRuns, getRelatedBundles } from "../contracts.js";
import { readCrucibleLink } from "../validation-links.js";
import { loadManifestRaw, listTasks } from "../../core/manifest.js";
import { loadVerifiedBundle } from "../../core/bundle.js";
import { normalizeBundleVerdict } from "../../core/verdict.js";
import { resolveDisplayName } from "../../core/test-names.js";
import { isSafeId as isSafeIdShared } from "../../utils/safe-id.js";

const RUNS_DIR = process.env["LUAK_RUNS_DIR"] ?? process.env["CRUCIBULUM_RUNS_DIR"] ?? join(process.cwd(), "runs");
const UI_PATH = join(import.meta.dirname, "..", "..", "ui", "index.html");

export function setCorsHeaders(req: IncomingMessage, res: ServerResponse): void {
  const origin = req.headers.origin ?? "";
  const isLocal = /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin);
  const allowed = (process.env["LUAK_ALLOWED_ORIGINS"] ?? process.env["CRUCIBLE_ALLOWED_ORIGINS"] ?? "")
    .split(",").map(o => o.trim()).filter(Boolean);
  if (isLocal || allowed.includes(origin)) {
    res.setHeader("Access-Control-Allow-Origin", origin);
  }
  res.setHeader("Access-Control-Allow-Methods", "GET,POST,PATCH,DELETE,OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
}

export function sendJSON(res: ServerResponse, status: number, data: unknown): void {
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
  });
  res.end(JSON.stringify(data));
}

export async function readBody(req: IncomingMessage): Promise<string> {
  const chunks: Buffer[] = [];
  let total = 0;
  const MAX_BODY = 2 * 1024 * 1024; // 2MB
  for await (const chunk of req) {
    const buf = chunk as Buffer;
    total += buf.length;
    if (total > MAX_BODY) throw new Error("Request body too large");
    chunks.push(buf);
  }
  return Buffer.concat(chunks).toString("utf-8");
}

/**
 * Parse a JSON body with bounded size. Returns [parsed, error]; error is a 400-ready message.
 */
export async function parseJsonBody<T = unknown>(req: IncomingMessage): Promise<{ ok: true; value: T } | { ok: false; error: string }> {
  try {
    const raw = await readBody(req);
    if (!raw.trim()) return { ok: true, value: {} as T };
    return { ok: true, value: JSON.parse(raw) as T };
  } catch (err) {
    return { ok: false, error: `Invalid JSON body: ${String(err)}` };
  }
}

/**
 * Validate a bundle/run ID for safe filesystem use. IDs must be alphanumeric, dash, underscore, dot.
 * Bundle IDs are generated by the system (see bundle.ts:buildBundle) but may come from user-supplied paths.
 */
export function isSafeId(id: string): boolean {
  // Delegate to the shared helper so the safe-segment definition lives in one
  // place (also rejects the literal "." and ".."). (Audit C5/M9.)
  return isSafeIdShared(id);
}

// mtime-invalidated cache for loadBundles. Every /api/leaderboard (and many
// other) reads re-walked runs/ and re-hashed every bundle — O(N·hash) per
// request, an amplification-DoS vector. We cache the parsed result keyed on a
// cheap digest of (filename, mtimeMs, size) for all bundle files; any
// add/remove/modify changes the digest and forces a fresh read, so the cache
// is always consistent with disk. Stat-only on a cache hit, not read+hash.
// (Audit M3.)
let bundleCache: { key: string; bundles: EvidenceBundle[] } | null = null;

function bundleDirSignature(): { key: string; files: string[] } | null {
  let entries: string[];
  try {
    entries = readdirSync(RUNS_DIR).filter(f => f.endsWith(".json") && !f.endsWith(".crucible.json")).sort();
  } catch {
    return null;
  }
  const parts: string[] = [];
  for (const f of entries) {
    try {
      const st = statSync(join(RUNS_DIR, f));
      parts.push(`${f}:${st.mtimeMs}:${st.size}`);
    } catch {
      parts.push(`${f}:gone`);
    }
  }
  return { key: parts.join("|"), files: entries };
}

// Older bundles (the pre-2026-06 "vision" batch — 180 of 6,554) predate several
// structures that every list/summary/verdict path assumes exist. A single
// missing one (timestamp_start, diff, security, provider_attempts) threw a
// TypeError and 500'd the ENTIRE list (/api/runs, /api/stats, /api/leaderboard,
// /api/receipts) even though the other 6,374 bundles were perfect. Backfill the
// canonical empty shapes (mirroring core/bundle.ts) so one legacy bundle can
// never blind every list view again.
function backfillLegacyBundle(bundle: EvidenceBundle, file: string): void {
  const b = bundle as unknown as Record<string, unknown>;
  const env = (b.environment ??= {}) as { timestamp_start?: string };
  if (!env.timestamp_start || Number.isNaN(new Date(env.timestamp_start).getTime())) {
    const m = file.match(/run_(\d{4}-\d{2}-\d{2})/);
    env.timestamp_start = m ? `${m[1]}T00:00:00.000Z` : new Date(0).toISOString();
  }
  if (!b.diff) b.diff = { files_changed: [], files_created: [], files_deleted: [], forbidden_paths_touched: [] };
  if (!b.security) b.security = { injection_scan: "clean", forbidden_paths_violations: 0, anti_cheat_violations: 0, workspace_escape_attempts: 0 };
  if (!Array.isArray(b.provider_attempts)) b.provider_attempts = [];
  const vr = b.verification_results as { integrity?: { score: number; details: Record<string, unknown>; violations: string[] } } | undefined;
  if (vr && !vr.integrity) vr.integrity = { score: 0, details: {}, violations: [] };
}

export function loadBundles(): EvidenceBundle[] {
  try {
    const sig = bundleDirSignature();
    if (!sig) return [];
    if (bundleCache && bundleCache.key === sig.key) return bundleCache.bundles;
    const files = sig.files;
    const bundles: EvidenceBundle[] = [];
    for (const f of files) {
      try {
        const raw = readFileSync(join(RUNS_DIR, f), "utf-8");
        // Re-verifies the bundle hash on every read; tampered/corrupted files get
        // trust.bundle_verified=false instead of silently inheriting the stored flag.
        const bundle = loadVerifiedBundle(raw, f);
        if (bundle) { backfillLegacyBundle(bundle, f); bundles.push(bundle); }
        else log("warn", "bundles", `Rejecting malformed bundle file ${f}`);
      } catch (err) {
        // Surface corruption instead of silently hiding it — operators need to see this in logs.
        log("warn", "bundles", `Skipping unparseable bundle file ${f}: ${String(err).slice(0, 120)}`);
      }
    }
    bundleCache = { key: sig.key, bundles };
    return bundles;
  } catch { return []; }
}

/**
 * Strict lookup by bundle_id. Does NOT fall back to task.id matching —
 * ambiguous dual lookup previously let a task id collide with a bundle id and
 * silently swap which bundle a caller thought they had.
 */
export function getBundleById(id: string): EvidenceBundle | null {
  // Defense in depth: reject obviously unsafe ids up front so no id-derived
  // path or lookup ever sees `../` etc., even though the match is in-memory. (M9)
  if (!isSafeId(id)) return null;
  try {
    const bundles = loadBundles();
    return bundles.find(b => b.bundle_id === id) ?? null;
  } catch { return null; }
}

/**
 * Lookup by the server-issued `run_id` that the runner stamped onto the
 * bundle. The UI's `runId` (returned from POST /api/run) flows through to
 * `bundle.run_id` so /api/runs/<runId> can hydrate even when the bundle's
 * filename slug differs from the run id (bundle ids now carry a random
 * suffix; run ids are crypto-random — they're never the same string).
 */
export function getBundleByRunId(runId: string): EvidenceBundle | null {
  if (!isSafeId(runId)) return null; // M9: reject unsafe ids uniformly
  try {
    const bundles = loadBundles();
    return bundles.find(b => b.run_id === runId) ?? null;
  } catch { return null; }
}

/** Explicit task-scoped lookup for callers that actually want every bundle for a task. */
export function getBundlesByTaskId(taskId: string): EvidenceBundle[] {
  try {
    return loadBundles().filter(b => b.task.id === taskId);
  } catch { return []; }
}

export function parseFamiliesParam(url: URL): ScoreFamily[] | null {
  const raw = (url.searchParams.get("families") ?? "").trim();
  if (!raw) return null;
  const families = raw.split(",").map(f => f.trim()).filter(Boolean) as ScoreFamily[];
  return families.length > 0 ? families : null;
}

export function parseTaskFamiliesParam(url: URL): string[] | null {
  const raw = (url.searchParams.get("task_families") ?? "").trim();
  if (!raw) return null;
  const families = [...new Set(raw.split(",").map((family) => family.trim()).filter(Boolean))];
  return families.length > 0 ? families : null;
}

export function parseBundleTaskFamiliesParam(url: URL): string[] | null {
  const taskFamilies = parseTaskFamiliesParam(url);
  if (taskFamilies && taskFamilies.length > 0) {
    return taskFamilies;
  }
  const scoreFamilies = parseFamiliesParam(url);
  const mapped = taskFamiliesForScoreFamilies(scoreFamilies);
  return mapped.length > 0 ? mapped : null;
}

/**
 * Resolved lane scope echoed back on every lane-aware endpoint so clients can
 * verify the response matches the request. `taskFamilies` is the canonical
 * filter; `scopeKey` is a stable, order-independent string the UI can use as a
 * cache key ("all" when nothing is applied).
 *
 * Scope flows end-to-end through one name — `task_families` — and this
 * helper is the single parsing point. Anything that branches on scope must go
 * through here; do NOT read searchParams for lane filtering anywhere else.
 */
export interface LaneScope {
  taskFamilies: string[] | null;
  scopeKey: string;
}

export function resolveLaneScope(url: URL): LaneScope {
  const taskFamilies = parseBundleTaskFamiliesParam(url);
  if (!taskFamilies || taskFamilies.length === 0) {
    return { taskFamilies: null, scopeKey: "all" };
  }
  const normalized = [...taskFamilies].sort();
  return { taskFamilies: normalized, scopeKey: normalized.join(",") };
}

export function filterBundlesByFamilies(bundles: EvidenceBundle[], families: ScoreFamily[] | null): EvidenceBundle[] {
  if (!families || families.length === 0) return bundles;
  const familySet = new Set(families);
  return bundles.filter(b => {
    const taskFamily = b.task.family;
    const mapped = taskFamily.startsWith("poison") ? "A"
      : taskFamily.startsWith("spec") ? "B"
      : taskFamily.startsWith("orchestration") ? "C"
      : taskFamily.startsWith("conversational") ? "D"
      : null;
    return mapped ? familySet.has(mapped) : true;
  });
}

export function filterBundlesByTaskFamilies(bundles: EvidenceBundle[], taskFamilies: string[] | null): EvidenceBundle[] {
  if (!taskFamilies || taskFamilies.length === 0) return bundles;
  const familySet = new Set(taskFamilies);
  return bundles.filter((bundle) => familySet.has(bundle.task.family));
}

export function listTaskDetails(): Array<Record<string, unknown>> {
  return listTasks().map((task) => {
    const manifest = loadManifestRaw(task.id);
    const isConversational = manifest.execution_mode === "conversational" || !manifest.task;
    const displayName = resolveDisplayName(manifest);
    return {
      id: manifest.id,
      suite_id: "v1",
      family: manifest.family,
      // `title` retained for backwards-compat with anything that still reads
      // it as the prominent label. New callers should prefer `display_name`,
      // which is the human-readable name (always defined).
      title: manifest.task?.title ?? manifest.description ?? manifest.id,
      display_name: displayName,
      difficulty: manifest.difficulty,
      execution_mode: manifest.execution_mode ?? "repo",
      time_limit_sec: manifest.constraints?.time_limit_sec ?? null,
      max_steps: manifest.constraints?.max_steps ?? null,
      network_allowed: manifest.constraints?.network_allowed ?? false,
      public_tests_command: manifest.verification?.public_tests_command ?? null,
      build_command: manifest.verification?.build_command ?? null,
      question_count: isConversational ? (manifest.questions?.length ?? 0) : null,
      diagnostic_purpose: manifest.metadata?.diagnostic_purpose ?? null,
      tags: manifest.metadata?.tags ?? [],
      benchmark_provenance: manifest.metadata?.benchmark_provenance ?? null,
    };
  });
}

export function listSuites(): Array<Record<string, unknown>> {
  const tasks = listTasks();
  const byFamily = new Map<string, number>();
  for (const task of tasks) {
    byFamily.set(task.family, (byFamily.get(task.family) ?? 0) + 1);
  }
  return [{
    id: "v1",
    label: "Luak v1",
    task_count: tasks.length,
    families: Array.from(byFamily.entries()).map(([family, count]) => ({ family, count })),
  }];
}

export function bundleSummary(bundle: EvidenceBundle, allBundles: EvidenceBundle[]): ReturnType<typeof summarizeBundle> {
  const relatedBundles = getRelatedBundles(allBundles, bundle);
  const repeats = countRepeatRuns(allBundles, bundle.task.id, bundle.agent.adapter, bundle.agent.model, bundle.agent.provider);
  return summarizeBundle(bundle, repeats, readCrucibleLink(bundle.bundle_id), relatedBundles);
}

export function getStats(bundles: EvidenceBundle[]): Record<string, unknown> {
  const totalRuns = bundles.length;
  const verdicts = bundles.map((bundle) => normalizeBundleVerdict(bundle));
  const passedRuns = verdicts.filter((verdict) => verdict.completionState === "PASS").length;
  const modelFails = verdicts.filter((verdict) => verdict.completionState === "FAIL" && verdict.failureOrigin === "MODEL").length;
  const notCompleteRuns = verdicts.filter((verdict) => verdict.completionState === "NC").length;
  const infraIssueRuns = verdicts.filter((verdict) => verdict.completionState === "NC" && ["PROVIDER", "NETWORK", "HARNESS", "UNKNOWN"].includes(verdict.failureOrigin ?? "")).length;
  const testJudgeIssueRuns = verdicts.filter((verdict) => verdict.completionState === "NC" && ["TEST", "JUDGE"].includes(verdict.failureOrigin ?? "")).length;
  const totalCost = bundles.reduce((sum, b) => sum + (b.usage.estimated_cost_usd ?? 0), 0);
  const totalTokens = bundles.reduce((sum, b) => sum + (b.usage.tokens_in ?? 0) + (b.usage.tokens_out ?? 0), 0);
  const uniqueModels = new Set(bundles.map(b => b.agent.model)).size;
  const uniqueTasks = new Set(bundles.map(b => b.task.id)).size;
  const scoredBundles = bundles.filter((bundle, index) => {
    const verdict = verdicts[index];
    return verdict.completionState !== "NC";
  });
  const avgScore = scoredBundles.length > 0 ? scoredBundles.reduce((sum, b) => sum + canonicalPercent(b.score.total), 0) / scoredBundles.length : 0;
  return {
    total_runs: totalRuns,
    passed_runs: passedRuns,
    pass_rate: totalRuns > 0 ? Math.round((passedRuns / totalRuns) * 100) : 0,
    model_fail_runs: modelFails,
    model_failure_rate: totalRuns > 0 ? Math.round((modelFails / totalRuns) * 100) : 0,
    infra_issue_runs: infraIssueRuns,
    infra_issue_rate: totalRuns > 0 ? Math.round((infraIssueRuns / totalRuns) * 100) : 0,
    test_judge_issue_runs: testJudgeIssueRuns,
    test_judge_issue_rate: totalRuns > 0 ? Math.round((testJudgeIssueRuns / totalRuns) * 100) : 0,
    not_complete_runs: notCompleteRuns,
    completion_rate: totalRuns > 0 ? Math.round(((totalRuns - notCompleteRuns) / totalRuns) * 100) : 0,
    nc_rate: totalRuns > 0 ? Math.round((notCompleteRuns / totalRuns) * 100) : 0,
    scored_runs: scoredBundles.length,
    avg_score: Math.round(avgScore * 100) / 100,
    total_cost_usd: Math.round(totalCost * 10000) / 10000,
    total_tokens: totalTokens,
    unique_models: uniqueModels,
    unique_tasks: uniqueTasks,
  };
}

export { RUNS_DIR, UI_PATH, log, canonicalPercent };
