/**
 * Luak — deterministic long-context fixture generator.
 *
 * The census found that the largest prompt in the entire 87-task corpus is
 * 1 166 characters. Luak therefore has no long-context measurement at all,
 * which for local models is the gap that matters most: context is the binding
 * constraint, and degradation inside the window looks exactly like incapacity
 * from the outside.
 *
 * Fixtures are **generated from authored templates**, never committed as large
 * blobs and never produced by a model. Committing a 32K-token log would put a
 * quarter of a megabyte of filler in git for every tier; worse, a
 * model-generated fixture measures agreement with the generating model rather
 * than correctness. Everything here comes from a hand-written corpus combined
 * by a seeded PRNG, so the same seed and tier always yield byte-identical text
 * with a stable hash.
 *
 * ## Characters are not tokens
 *
 * Tiers are *named* for token budgets and *built* to character targets, using a
 * crude ratio. That ratio is fixture-generation metadata and nothing else. The
 * real token count is whatever the model's own tokenizer says when the fixture
 * is executed, and it is recorded then, from the runtime, with
 * `tokenCountSource: "runtime_tokenizer"`. Nothing in this file may be reported
 * as a token measurement — a character count dressed as a token count would
 * make every context-tier claim wrong by an unknown factor that varies by
 * tokenizer.
 */
import { createHash } from "node:crypto";

export const CONTEXT_GENERATOR_VERSION = "local-context-generator-1.0.0" as const;

/**
 * Characters per token, used *only* to size generated text.
 *
 * A rough English-prose average. Deliberately not tuned per model: tuning it
 * would imply a precision this number does not have and cannot have, since the
 * tokenizer is not known at generation time.
 */
export const NOMINAL_CHARS_PER_TOKEN = 4;

export interface ContextTier {
  readonly label: string;
  /** Nominal token budget the tier is named for. Not a measurement. */
  readonly nominalTokens: number;
  /** Character target used to build the fixture. Generation metadata only. */
  readonly targetChars: number;
  /**
   * Whether this tier may be generated by default. 64K is defined but gated:
   * emitting it for a runtime served at 32K would only ever produce
   * `local_context_overflow`, which measures the harness, not the model.
   */
  readonly requiresAdapterSupport: boolean;
}

export const CONTEXT_TIERS: readonly ContextTier[] = Object.freeze([
  { label: "control", nominalTokens: 512, targetChars: 512 * NOMINAL_CHARS_PER_TOKEN, requiresAdapterSupport: false },
  { label: "8k", nominalTokens: 8_192, targetChars: 8_192 * NOMINAL_CHARS_PER_TOKEN, requiresAdapterSupport: false },
  { label: "16k", nominalTokens: 16_384, targetChars: 16_384 * NOMINAL_CHARS_PER_TOKEN, requiresAdapterSupport: false },
  { label: "32k", nominalTokens: 32_768, targetChars: 32_768 * NOMINAL_CHARS_PER_TOKEN, requiresAdapterSupport: false },
  { label: "64k", nominalTokens: 65_536, targetChars: 65_536 * NOMINAL_CHARS_PER_TOKEN, requiresAdapterSupport: true },
]);

export function tierByLabel(label: string): ContextTier | undefined {
  return CONTEXT_TIERS.find((t) => t.label === label);
}

/** Where a planted item sits in the document. The whole point of the exercise. */
export type Position = "beginning" | "middle" | "end";
export const POSITIONS: readonly Position[] = ["beginning", "middle", "end"];

/** What a planted line is, so a scorer can check the right thing about it. */
export type PlantKind =
  /** The fact the question asks for. Exactly one per required-fact id. */
  | "required_fact"
  /** Looks like the required fact, is not. Tests discrimination, not recall. */
  | "distractor"
  /** Same identifier shape, different value. Tests precise matching. */
  | "repeated_identifier"
  /** Directly contradicts a required fact. The model must notice, not average. */
  | "contradiction"
  /** An instruction inside the evidence. Must be treated as data. */
  | "injection"
  /** A marker saying content was withheld. Must be reported, not invented around. */
  | "omitted_marker";

export interface PlantedItem {
  readonly id: string;
  readonly kind: PlantKind;
  readonly position: Position;
  /** 1-based line number in the generated document. */
  readonly line: number;
  readonly text: string;
  /** For required_fact: the value a correct answer must contain. */
  readonly answer: string | null;
}

export interface GeneratedFixture {
  readonly generatorVersion: typeof CONTEXT_GENERATOR_VERSION;
  readonly fixtureId: string;
  readonly tier: string;
  readonly seed: number;
  readonly text: string;
  readonly lineCount: number;
  /**
   * Generation metadata. Explicitly *not* a token count — see the file header.
   * The name carries the warning so it cannot be misread at a call site.
   */
  readonly generationChars: number;
  readonly nominalTokensForTier: number;
  readonly tokenCountSource: "not_measured";
  readonly planted: readonly PlantedItem[];
  /** sha256 of the generated text. Stable for a given (fixtureId, tier, seed). */
  readonly contentHash: string;
}

// ---------------------------------------------------------------------------
// Deterministic PRNG
// ---------------------------------------------------------------------------

/**
 * mulberry32. Small, fast, and — the only property that matters here —
 * completely determined by its seed. `Math.random` would make every fixture
 * hash unstable and every "identical run" claim false.
 */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function pick<T>(rng: () => number, xs: readonly T[]): T {
  return xs[Math.floor(rng() * xs.length)] as T;
}

// ---------------------------------------------------------------------------
// Authored filler corpus
// ---------------------------------------------------------------------------

/**
 * Hand-written log-shaped filler.
 *
 * Deliberately plausible and deliberately uninformative: it must look like the
 * surrounding noise of a real CI run so that finding the planted fact is a
 * genuine retrieval problem, while containing nothing a scorer could mistake
 * for an answer. Placeholders are substituted from the pools below.
 */
const FILLER_TEMPLATES: readonly string[] = [
  "PASS  {suite} > {case} ({ms}ms)",
  "  ok {n} - {case}",
  "[{level}] {component}: {verb} {noun} in {ms}ms",
  "  at {component}.{verb} ({file}:{n}:{n2})",
  "{component}: cache {hitmiss} for key {key}",
  "  → {verb} {noun} (attempt {n}/3)",
  "[{level}] {component}: connection pool size {n}, active {n2}",
  "PASS  {suite} > {case}",
  "  info: {noun} {verb} without incident",
  "{component}: {n} {noun} processed, {n2} skipped",
];

const SUITES = ["auth.test.ts", "billing.test.ts", "search.test.ts", "queue.test.ts", "user.test.ts", "report.test.ts"];
const CASES = [
  "returns 200 for a valid request", "rejects an expired token", "paginates results",
  "normalises whitespace", "retries on transient failure", "emits a metric",
  "closes the connection", "validates the payload", "sorts deterministically",
];
const COMPONENTS = ["authService", "billingWorker", "searchIndex", "queueDrain", "userRepo", "reportBuilder"];
const VERBS = ["resolved", "flushed", "indexed", "validated", "serialised", "committed"];
const NOUNS = ["records", "sessions", "documents", "envelopes", "batches", "entries"];
const FILES = ["src/auth/session.ts", "src/billing/invoice.ts", "src/search/index.ts", "src/queue/drain.ts"];
const LEVELS = ["INFO", "DEBUG", "INFO", "INFO"];

function fillerLine(rng: () => number): string {
  return pick(rng, FILLER_TEMPLATES)
    .replace("{suite}", pick(rng, SUITES))
    .replace(/\{case\}/g, pick(rng, CASES))
    .replace(/\{component\}/g, pick(rng, COMPONENTS))
    .replace(/\{verb\}/g, pick(rng, VERBS))
    .replace(/\{noun\}/g, pick(rng, NOUNS))
    .replace("{file}", pick(rng, FILES))
    .replace("{level}", pick(rng, LEVELS))
    .replace("{hitmiss}", rng() < 0.5 ? "hit" : "miss")
    .replace("{key}", `k-${Math.floor(rng() * 9000 + 1000)}`)
    .replace("{ms}", String(Math.floor(rng() * 400 + 5)))
    .replace(/\{n2\}/g, String(Math.floor(rng() * 90 + 2)))
    .replace(/\{n\}/g, String(Math.floor(rng() * 900 + 10)));
}

// ---------------------------------------------------------------------------
// Plant specifications
// ---------------------------------------------------------------------------

export interface PlantSpec {
  readonly id: string;
  readonly kind: PlantKind;
  readonly position: Position;
  readonly text: string;
  readonly answer?: string;
}

export interface GenerateOptions {
  readonly fixtureId: string;
  readonly tier: string;
  readonly seed: number;
  readonly plants: readonly PlantSpec[];
  /** Prepended verbatim, before any filler. Used for headers a scorer cites. */
  readonly preamble?: readonly string[];
}

/**
 * Build a fixture.
 *
 * Placement is by *position band*, not by exact line: beginning is the first
 * third, middle the second, end the last. Within a band the offset is drawn
 * from the seeded PRNG, so it is stable per seed but not identical across
 * fixtures — a model must not be able to learn "the answer is on line 40".
 */
export function generateContextFixture(opts: GenerateOptions): GeneratedFixture {
  const tier = tierByLabel(opts.tier);
  if (!tier) throw new Error(`unknown context tier: ${opts.tier}`);

  const rng = mulberry32(opts.seed);
  const preamble = [...(opts.preamble ?? [])];

  // Build filler to the character target, leaving room for the plants.
  const plantChars = opts.plants.reduce((a, p) => a + p.text.length + 1, 0);
  const preambleChars = preamble.reduce((a, l) => a + l.length + 1, 0);
  const budget = Math.max(0, tier.targetChars - plantChars - preambleChars);

  const filler: string[] = [];
  let used = 0;
  while (used < budget) {
    const line = fillerLine(rng);
    filler.push(line);
    used += line.length + 1;
  }
  // A fixture with nowhere to hide anything is not a retrieval test.
  if (filler.length < opts.plants.length * 3) {
    throw new Error(
      `tier ${opts.tier} is too small for ${opts.plants.length} plants: ` +
        `${filler.length} filler lines available, need at least ${opts.plants.length * 3}`,
    );
  }

  // Choose a distinct insertion index per plant, inside its position band.
  const n = filler.length;
  const bands: Record<Position, [number, number]> = {
    beginning: [0, Math.floor(n / 3)],
    middle: [Math.floor(n / 3), Math.floor((2 * n) / 3)],
    end: [Math.floor((2 * n) / 3), n],
  };
  const taken = new Set<number>();
  const placements = opts.plants.map((p) => {
    const [lo, hi] = bands[p.position];
    let idx = lo + Math.floor(rng() * Math.max(1, hi - lo));
    while (taken.has(idx)) idx = lo + ((idx - lo + 1) % Math.max(1, hi - lo));
    taken.add(idx);
    return { plant: p, idx };
  });

  // Insert from the back so earlier indices stay valid.
  const lines = [...filler];
  for (const { plant, idx } of [...placements].sort((a, b) => b.idx - a.idx)) {
    lines.splice(idx, 0, plant.text);
  }

  const all = [...preamble, ...lines];
  const text = all.join("\n");

  // Resolve final 1-based line numbers by locating each plant's exact text.
  const planted: PlantedItem[] = placements
    .map(({ plant }) => {
      const line = all.findIndex((l) => l === plant.text) + 1;
      if (line === 0) throw new Error(`plant ${plant.id} vanished during assembly`);
      return {
        id: plant.id,
        kind: plant.kind,
        position: plant.position,
        line,
        text: plant.text,
        answer: plant.answer ?? null,
      };
    })
    .sort((a, b) => a.line - b.line);

  return {
    generatorVersion: CONTEXT_GENERATOR_VERSION,
    fixtureId: opts.fixtureId,
    tier: tier.label,
    seed: opts.seed,
    text,
    lineCount: all.length,
    generationChars: text.length,
    nominalTokensForTier: tier.nominalTokens,
    tokenCountSource: "not_measured",
    planted,
    contentHash: `sha256:${createHash("sha256").update(text, "utf8").digest("hex")}`,
  };
}

/**
 * Assert that a planted item's text really is at the line the manifest claims.
 *
 * The scorers trust these line numbers absolutely — a citation is judged
 * correct by comparing against them — so a drift between manifest and document
 * would silently invert every grounding verdict.
 */
export function verifyPlacement(f: GeneratedFixture): { ok: boolean; problems: string[] } {
  const lines = f.text.split("\n");
  const problems: string[] = [];
  for (const p of f.planted) {
    const actual = lines[p.line - 1];
    if (actual !== p.text) {
      problems.push(`${p.id}: manifest says line ${p.line}, document has ${JSON.stringify(actual)}`);
    }
  }
  const dupes = f.planted.filter((p) => lines.filter((l) => l === p.text).length > 1);
  for (const d of dupes) {
    problems.push(`${d.id}: its text appears more than once, so a citation cannot be checked`);
  }
  return { ok: problems.length === 0, problems };
}
